name: upgrader
description: Flutter package for prompting users to upgrade when there is a newer version of the app in the store.
version: 3.3.0
homepage: https://github.com/larryaasen/upgrader

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  device_info: ^2.0.0
  http: ^0.12.0
  package_info: ^2.0.0
  shared_preferences: ^0.5.8
  url_launcher: ^6.0.2
  version:  ^2.0.0
  xml: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # From Dart Team: Mock library for Dart inspired by Mockito.
  mockito: ^4.0.0
  pedantic: ^1.11.0
 
flutter: